version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/training
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: sa

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: training
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
